project_id = "zumagxrwfluuknanmlpz"

[auth]
site_url = "https://xpiritapp.vercel.app"
additional_redirect_urls = [
  "https://xpiritapp.vercel.app",
  "https://xpiritapp.vercel.app/**",
  "http://localhost:3000",
  "http://localhost:8081"
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8
